export type ClienteStatus = 'ativo' | 'inativo' | 'bloqueado' | 'suspenso';
export type TipoPessoa = 'fisica' | 'juridica';
export type ClassificacaoChave = 'cliente' | 'fornecedor' | 'transportadora';

export interface Classificacao { chave: ClassificacaoChave; nome: string; }
export interface ContatoCliente { id?: number; nome: string; cargo?: string | null; departamento?: string | null; telefone?: string | null; whatsapp?: string | null; email?: string | null; aprova_orcamentos: boolean; is_principal: boolean; }
export interface EnderecoCobranca { id?: number; tipo?: 'cobranca'; cep: string; logradouro: string; numero?: string | null; complemento?: string | null; bairro?: string | null; cidade: string; estado: string; }
export interface ResponsavelCliente { id: number; name: string; }
export interface ClienteResumo { id: number; uuid?: string | null; codigo: string; tipo_pessoa: TipoPessoa; razao_social: string; nome_fantasia?: string | null; cpf_cnpj?: string | null; status: ClienteStatus; segmento?: string | null; email?: string | null; telefone?: string | null; endereco_cobranca?: EnderecoCobranca | null; classificacoes?: Classificacao[]; ultimo_pedido_realizado?: string | null; responsavel?: ResponsavelCliente | null; pedidos_count?: number; }
export interface ClienteDetalhado extends ClienteResumo { inscricao_estadual?: string | null; inscricao_municipal?: string | null; condicao_pagamento_padrao?: string | null; limite_faturamento?: string | number | null; sem_limite_faturamento?: boolean; cliente_ativo_desde?: string | null; observacoes_internas?: string | null; matriz?: { id: number; codigo: string; nome: string } | null; filiais?: Array<{ id: number; codigo: string; nome: string }>; contatos: ContatoCliente[]; documentos?: Array<{ id: number; tipo: string; nome_original: string; nome_exibicao?: string | null; created_at?: string }>; obras?: Array<{ id: number; codigo: string; nome: string; status: string }>; created_at?: string | null; updated_at?: string | null; }
export interface ClientePayload { tipo_pessoa: TipoPessoa; razao_social: string; nome_fantasia?: string; cpf_cnpj: string; inscricao_estadual?: string; inscricao_municipal?: string; segmento: string; condicao_pagamento_padrao?: string; limite_faturamento?: number | null; sem_limite_faturamento?: boolean; status: ClienteStatus; matriz_id?: number | null; responsavel_id?: number | null; observacoes_internas?: string; classificacoes: ClassificacaoChave[]; endereco_cobranca: EnderecoCobranca; contatos: ContatoCliente[]; }
export interface UsuarioOpcao { id: number; name: string; }
export interface ClienteFilters { page?: number; limit?: number; search?: string; status?: string; cidade?: string; classificacao?: string; matriz_id?: string; sort?: 'codigo' | 'razao_social' | 'nome_fantasia' | 'status' | 'created_at'; direction?: 'asc' | 'desc'; }
export interface PaginatedClientes { data: ClienteResumo[]; current_page: number; last_page: number; per_page: number; total: number; from: number | null; to: number | null; }
