import { useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, MapPin } from 'lucide-react';
import { Button, Input, Select, Card, CardHeader, CardBody, CardTitle } from '../../components/ui';
import { useForm } from '../../hooks/useForm';
import { useApi } from '../../hooks/useApi';
import * as clienteService from '../../services/comercial/cliente';
import type { CreateClienteDTO } from '../../types/comercial';
import '../../styles/comercial.css';

interface ClienteFormValues extends CreateClienteDTO {}
const CAMPOS: Array<keyof ClienteFormValues> = ['tipo', 'nome', 'email', 'documento', 'telefone', 'empresa', 'cidade', 'estado', 'cep', 'logradouro', 'numero', 'complemento', 'bairro'];
const ESTADOS = ['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'];
const digits = (value: string) => value.replace(/\D/g, '');
const documento = (value: string) => { const v = digits(value).slice(0, 14); return v.length <= 11 ? v.replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d{1,2})$/, '$1-$2') : v.replace(/(\d{2})(\d)/, '$1.$2').replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d)/, '$1/$2').replace(/(\d{4})(\d{1,2})$/, '$1-$2'); };
const telefone = (value: string) => { const v = digits(value).slice(0, 11); return v.replace(/(\d{2})(\d)/, '($1) $2').replace(/(\d{5})(\d)/, '$1-$2'); };
const cepMask = (value: string) => digits(value).slice(0, 8).replace(/(\d{5})(\d)/, '$1-$2');

export default function ClienteForm() {
  const navigate = useNavigate(); const { id } = useParams<{ id: string }>(); const isEdicao = Boolean(id); const [status, setStatus] = useState<'ativo' | 'inativo'>('ativo'); const [buscandoCep, setBuscandoCep] = useState(false);
  const buscarCliente = useCallback(() => id ? clienteService.obterCliente(Number(id)) : Promise.resolve(null), [id]);
  const { data: cliente, refetch: carregarCliente } = useApi(buscarCliente);
  const { values, errors, touched, isSubmitting, handleChange, handleBlur, handleSubmit, setFieldValue } = useForm<ClienteFormValues>({
    initialValues: { tipo: 'juridica', nome: '', email: '', documento: '', telefone: '', empresa: '', cidade: '', estado: '', cep: '', logradouro: '', numero: '', complemento: '', bairro: '' },
    validate: (form) => { const err = Object.fromEntries(CAMPOS.map((campo) => [campo, undefined])) as Record<keyof ClienteFormValues, string | undefined>; if (!form.nome.trim()) err.nome = 'Obrigatório'; if (!form.email.trim()) err.email = 'Obrigatório'; if (!form.telefone.trim()) err.telefone = 'Obrigatório'; if (!form.empresa.trim()) err.empresa = 'Obrigatório'; if (!form.cidade.trim()) err.cidade = 'Obrigatório'; if (!form.estado) err.estado = 'Obrigatório'; if (!form.cep) { if (!form.logradouro?.trim()) err.logradouro = 'Informe o endereço'; if (!form.numero?.trim()) err.numero = 'Informe o número'; if (!form.bairro?.trim()) err.bairro = 'Informe o bairro'; } return err; },
    onSubmit: async (form) => { if (isEdicao) await clienteService.atualizarCliente(Number(id), { ...form, status }); else await clienteService.criarCliente(form); navigate('/comercial/clientes'); },
  });
  useEffect(() => { if (isEdicao) carregarCliente(); }, [isEdicao, carregarCliente]);
  useEffect(() => { if (!cliente) return; CAMPOS.forEach((campo) => setFieldValue(campo, cliente[campo] ?? '')); setStatus(cliente.status === 'inativo' ? 'inativo' : 'ativo'); }, [cliente, setFieldValue]);
  const masked = (field: 'documento' | 'telefone' | 'cep', formatter: (value: string) => string) => (event: React.ChangeEvent<HTMLInputElement>) => { const value = formatter(event.target.value); setFieldValue(field, value); };
  const consultarCep = async () => { const codigo = digits(values.cep || ''); if (codigo.length !== 8) return; setBuscandoCep(true); try { const resposta = await fetch(`https://viacep.com.br/ws/${codigo}/json/`); const dados = await resposta.json(); if (!dados.erro) { setFieldValue('logradouro', dados.logradouro || ''); setFieldValue('bairro', dados.bairro || ''); setFieldValue('cidade', dados.localidade || ''); setFieldValue('estado', dados.uf || ''); } } finally { setBuscandoCep(false); } };
  const alternarStatus = async () => { const novoStatus = status === 'ativo' ? 'inativo' : 'ativo'; try { await clienteService.atualizarCliente(Number(id), { status: novoStatus }); setStatus(novoStatus); } catch { window.alert('Não foi possível atualizar o status do cliente.'); } };
  return <div className="comercial-container customer-form"><div className="comercial-header"><Button variant="ghost" icon={<ArrowLeft size={20} />} onClick={() => navigate('/comercial/clientes')}>Voltar</Button>{isEdicao && <Button variant={status === 'ativo' ? 'danger' : 'primary'} onClick={alternarStatus}>{status === 'ativo' ? 'Inativar cliente' : 'Ativar cliente'}</Button>}</div>
    <Card><CardHeader><CardTitle>{isEdicao ? 'Editar cliente' : 'Novo cliente'}</CardTitle><p className="customer-form-note">Campos com * são obrigatórios. Endereço pode ser preenchido automaticamente pelo CEP.</p></CardHeader><CardBody><form onSubmit={handleSubmit} className="customer-grid">
      <div className="form-group"><label>Tipo *</label><Select name="tipo" value={values.tipo} onChange={handleChange} options={[{ value: 'juridica', label: 'Pessoa jurídica' }, { value: 'fisica', label: 'Pessoa física' }]} /></div><div className="form-group"><label>{values.tipo === 'juridica' ? 'Razão social *' : 'Nome completo *'}</label><Input name="nome" value={values.nome} onChange={handleChange} onBlur={handleBlur} error={touched.nome ? errors.nome : undefined} /></div><div className="form-group"><label>CPF / CNPJ</label><Input name="documento" value={values.documento || ''} onChange={masked('documento', documento)} placeholder="Somente números" /></div>
      <div className="form-group"><label>E-mail *</label><Input name="email" type="email" value={values.email} onChange={handleChange} onBlur={handleBlur} error={touched.email ? errors.email : undefined} /></div><div className="form-group"><label>Telefone *</label><Input name="telefone" value={values.telefone} onChange={masked('telefone', telefone)} onBlur={handleBlur} error={touched.telefone ? errors.telefone : undefined} placeholder="Somente números" /></div><div className="form-group"><label>Nome fantasia / empresa *</label><Input name="empresa" value={values.empresa} onChange={handleChange} onBlur={handleBlur} error={touched.empresa ? errors.empresa : undefined} /></div>
      <div className="form-group"><label>CEP</label><Input name="cep" value={values.cep || ''} onChange={masked('cep', cepMask)} onBlur={consultarCep} placeholder="Somente números" icon={<MapPin size={16} />} hint={buscandoCep ? 'Buscando endereço...' : undefined} /></div><div className="form-group customer-wide"><label>Logradouro {!values.cep && '*'}</label><Input name="logradouro" value={values.logradouro || ''} onChange={handleChange} onBlur={handleBlur} error={touched.logradouro ? errors.logradouro : undefined} /></div><div className="form-group"><label>Número {!values.cep && '*'}</label><Input name="numero" value={values.numero || ''} onChange={handleChange} onBlur={handleBlur} error={touched.numero ? errors.numero : undefined} /></div><div className="form-group"><label>Complemento</label><Input name="complemento" value={values.complemento || ''} onChange={handleChange} /></div><div className="form-group"><label>Bairro {!values.cep && '*'}</label><Input name="bairro" value={values.bairro || ''} onChange={handleChange} onBlur={handleBlur} error={touched.bairro ? errors.bairro : undefined} /></div><div className="form-group"><label>Cidade *</label><Input name="cidade" value={values.cidade} onChange={handleChange} onBlur={handleBlur} error={touched.cidade ? errors.cidade : undefined} /></div><div className="form-group"><label>UF *</label><Select name="estado" value={values.estado} onChange={handleChange} options={ESTADOS.map((uf) => ({ value: uf, label: uf }))} placeholder="UF" error={touched.estado ? errors.estado : undefined} /></div>
      <div className="form-actions customer-actions"><Button type="button" variant="secondary" onClick={() => navigate('/comercial/clientes')}>Cancelar</Button><Button type="submit" loading={isSubmitting}>{isEdicao ? 'Salvar alterações' : 'Cadastrar cliente'}</Button></div>
    </form></CardBody></Card></div>;
}
