import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, Building2, CreditCard, FileText, MapPin, Paperclip, Plus, Trash2, UsersRound } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { Button, Input, Select } from '../../components/ui';
import { clientesService } from '../../services/clientes';
import type { ClassificacaoChave, ClienteDetalhado, ClientePayload, ContatoCliente, EnderecoCobranca, UsuarioOpcao } from '../../types/clientes';
import type { ApiError } from '../../types/api';
import '../../styles/clientes-module.css';

type Section = 'gerais' | 'contatos' | 'cobranca' | 'comercial' | 'documentos' | 'filiais' | 'obras' | 'timeline';
const sections: Array<[Section, string, typeof FileText]> = [['gerais', 'Dados Gerais', FileText], ['contatos', 'Contatos', UsersRound], ['cobranca', 'Endereço de Cobrança', MapPin], ['comercial', 'Condições Comerciais', CreditCard], ['documentos', 'Documentos', Paperclip], ['filiais', 'Filiais', Building2], ['obras', 'Obras', Building2], ['timeline', 'Timeline', FileText]];
const states = ['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO'];
const emptyAddress: EnderecoCobranca = { cep: '', logradouro: '', numero: '', complemento: '', bairro: '', cidade: '', estado: 'RS' };
const emptyContact = (): ContatoCliente => ({ nome: '', cargo: '', departamento: '', telefone: '', whatsapp: '', email: '', aprova_orcamentos: false, is_principal: false });
const digits = (value: string) => value.replace(/\D/g, '');
const docMask = (value: string) => { const v = digits(value).slice(0, 14); return v.length <= 11 ? v.replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d{1,2})$/, '$1-$2') : v.replace(/(\d{2})(\d)/, '$1.$2').replace(/(\d{3})(\d)/, '$1.$2').replace(/(\d{3})(\d)/, '$1/$2').replace(/(\d{4})(\d{1,2})$/, '$1-$2'); };
const phoneMask = (value: string) => { const v = digits(value).slice(0, 11); return v.replace(/(\d{2})(\d)/, '($1) $2').replace(/(\d{5})(\d)/, '$1-$2'); };
const cepMask = (value: string) => digits(value).slice(0, 8).replace(/(\d{5})(\d)/, '$1-$2');

export default function ClienteForm() {
  const { id } = useParams<{ id: string }>(); const navigate = useNavigate(); const editing = Boolean(id); const [section, setSection] = useState<Section>('gerais'); const [loading, setLoading] = useState(editing); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [branches, setBranches] = useState<Array<{ id: number; codigo: string; razao_social: string }>>([]); const [users, setUsers] = useState<UsuarioOpcao[]>([]); const [cepLoading, setCepLoading] = useState(false); const [cepError, setCepError] = useState<string | null>(null); const queriedCep = useRef<string | null>(null);
  const [form, setForm] = useState<ClientePayload>({ tipo_pessoa: 'juridica', razao_social: '', nome_fantasia: '', cpf_cnpj: '', inscricao_estadual: '', inscricao_municipal: '', segmento: '', condicao_pagamento_padrao: '', limite_faturamento: null, sem_limite_faturamento: false, status: 'ativo', matriz_id: null, responsavel_id: null, observacoes_internas: '', classificacoes: ['cliente'], endereco_cobranca: emptyAddress, contatos: [emptyContact()] });
  const update = <K extends keyof ClientePayload>(key: K, value: ClientePayload[K]) => setForm((current) => ({ ...current, [key]: value }));
  const hydrate = (client: ClienteDetalhado) => setForm({ tipo_pessoa: client.tipo_pessoa, razao_social: client.razao_social, nome_fantasia: client.nome_fantasia || '', cpf_cnpj: client.cpf_cnpj || '', inscricao_estadual: client.inscricao_estadual || '', inscricao_municipal: client.inscricao_municipal || '', segmento: client.segmento || '', condicao_pagamento_padrao: client.condicao_pagamento_padrao || '', limite_faturamento: client.sem_limite_faturamento ? null : Number(client.limite_faturamento ?? 0), sem_limite_faturamento: Boolean(client.sem_limite_faturamento), status: client.status, matriz_id: client.matriz?.id || null, responsavel_id: client.responsavel?.id || null, observacoes_internas: client.observacoes_internas || '', classificacoes: client.classificacoes?.map((item) => item.chave) || [], endereco_cobranca: client.endereco_cobranca || emptyAddress, contatos: client.contatos?.length ? client.contatos : [emptyContact()] });
  const load = useCallback(async () => { if (!id) return; try { hydrate(await clientesService.obter(Number(id))); } catch (caught) { setError((caught as ApiError).message); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); void clientesService.listar({ limit: 100, sort: 'razao_social', direction: 'asc' }).then((result) => setBranches(result.data)).catch(() => undefined); void clientesService.opcoesResponsaveis().then(setUsers).catch(() => undefined); }, [load]);
  const lookupCep = useCallback(async (force = false) => { const cep = digits(form.endereco_cobranca.cep); if (cep.length !== 8 || (!force && queriedCep.current === cep)) return; queriedCep.current = cep; setCepLoading(true); setCepError(null); try { const response = await fetch(`https://viacep.com.br/ws/${cep}/json/`); const result = await response.json() as { erro?: boolean; logradouro?: string; bairro?: string; localidade?: string; uf?: string }; if (result.erro) { setCepError('CEP não encontrado. Preencha manualmente.'); return; } update('endereco_cobranca', { ...form.endereco_cobranca, logradouro: result.logradouro || '', bairro: result.bairro || '', cidade: result.localidade || '', estado: result.uf || '' }); } catch { setCepError('Não foi possível consultar o CEP. Tente novamente ou preencha manualmente.'); } finally { setCepLoading(false); } }, [form.endereco_cobranca]);
  useEffect(() => { const cep = digits(form.endereco_cobranca.cep); if (cep.length !== 8) { queriedCep.current = null; setCepError(null); return; } const timer = window.setTimeout(() => void lookupCep(), 350); return () => window.clearTimeout(timer); }, [form.endereco_cobranca.cep, lookupCep]);
  const validation = useMemo(() => { if (!form.razao_social.trim()) return 'Informe o nome.'; if (![11, 14].includes(digits(form.cpf_cnpj).length)) return 'Informe CPF/CNPJ válido.'; if (form.tipo_pessoa === 'juridica' && !form.nome_fantasia?.trim()) return 'Informe o nome fantasia.'; if (!form.segmento.trim()) return 'Informe o segmento.'; if (!form.classificacoes.length) return 'Selecione uma classificação.'; if (form.contatos.some((contact) => !contact.nome.trim() || (!contact.email && !contact.telefone && !contact.whatsapp))) return 'Cada contato precisa de nome e um canal.'; if (!form.endereco_cobranca.cep || !form.endereco_cobranca.logradouro || !form.endereco_cobranca.cidade) return 'Preencha o endereço de cobrança.'; return null; }, [form]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (validation) { setError(validation); setSection('gerais'); return; } setSaving(true); setError(null); try { if (editing) await clientesService.atualizar(Number(id), form); else await clientesService.criar(form); navigate('/comercial/clientes'); } catch (caught) { const api = caught as ApiError; const fields = (api.data as { errors?: Record<string, string[]> } | undefined)?.errors; setError(fields ? Object.values(fields).flat().join(' ') : api.message); } finally { setSaving(false); } };
  const changeType = (type: ClientePayload['tipo_pessoa']) => { if (type === form.tipo_pessoa) return; if (type === 'fisica' && (form.nome_fantasia || form.inscricao_estadual || form.inscricao_municipal) && !window.confirm('Os campos empresariais serão removidos. Deseja continuar?')) return; update('tipo_pessoa', type); if (type === 'fisica') setForm((current) => ({ ...current, tipo_pessoa: type, nome_fantasia: '', inscricao_estadual: '', inscricao_municipal: '' })); };
  const toggleClass = (key: ClassificacaoChave) => update('classificacoes', form.classificacoes.includes(key) ? form.classificacoes.filter((item) => item !== key) : [...form.classificacoes, key]);
  const updateContact = (index: number, key: keyof ContatoCliente, value: string | boolean) => update('contatos', form.contatos.map((contact, position) => position === index ? { ...contact, [key]: value } : contact));
  if (loading) return <div className="clientes-skeleton" />;
  return <div className="clientes-module cliente-form-layout"><header className="clientes-header"><div><Button variant="ghost" size="sm" icon={<ArrowLeft size={16} />} onClick={() => navigate('/comercial/clientes')}>Voltar</Button><h1>{editing ? 'Editar cliente' : 'Novo cliente'}</h1><p>Cadastro comercial e dados de relacionamento.</p></div></header>{error && <div className="clientes-feedback">{error}</div>}<form className="cliente-form-shell" onSubmit={submit}><aside className="cliente-section-menu">{sections.map(([key, label]) => <button type="button" className={section === key ? 'active' : ''} onClick={() => setSection(key)} key={key}>{label}</button>)}</aside><section className="cliente-form-panel">
    {section === 'gerais' && <div className="cliente-form-grid"><div><label>Tipo de pessoa</label><Select value={form.tipo_pessoa} onChange={(event) => changeType(event.target.value as ClientePayload['tipo_pessoa'])} options={[{ value: 'juridica', label: 'Pessoa jurídica' }, { value: 'fisica', label: 'Pessoa física' }]} /></div><div className="wide"><label>{form.tipo_pessoa === 'fisica' ? 'Nome completo *' : 'Razão social *'}</label><Input value={form.razao_social} onChange={(event) => update('razao_social', event.target.value)} /></div>{form.tipo_pessoa === 'juridica' && <><div><label>Nome fantasia *</label><Input value={form.nome_fantasia || ''} onChange={(event) => update('nome_fantasia', event.target.value)} /></div><div><label>CNPJ *</label><Input value={docMask(form.cpf_cnpj)} onChange={(event) => update('cpf_cnpj', digits(event.target.value))} /></div><div><label>Inscrição estadual</label><Input value={form.inscricao_estadual || ''} onChange={(event) => update('inscricao_estadual', event.target.value)} /></div><div><label>Inscrição municipal</label><Input value={form.inscricao_municipal || ''} onChange={(event) => update('inscricao_municipal', event.target.value)} /></div></>}{form.tipo_pessoa === 'fisica' && <div><label>CPF *</label><Input value={docMask(form.cpf_cnpj)} onChange={(event) => update('cpf_cnpj', digits(event.target.value))} /></div>}<div><label>Segmento *</label><Input value={form.segmento} onChange={(event) => update('segmento', event.target.value)} /></div><div><label>Status</label><Select value={form.status} onChange={(event) => update('status', event.target.value as ClientePayload['status'])} options={[{ value: 'ativo', label: 'Ativo' }, { value: 'inativo', label: 'Inativo' }, { value: 'bloqueado', label: 'Bloqueado' }]} /></div><div><label>Matriz (quando filial)</label><Select value={form.matriz_id || ''} onChange={(event) => update('matriz_id', event.target.value ? Number(event.target.value) : null)} options={[{ value: '', label: 'Cadastro independente / matriz' }, ...branches.filter((branch) => branch.id !== Number(id)).map((branch) => ({ value: branch.id, label: `${branch.codigo} · ${branch.razao_social}` }))]} /></div><div className="full"><label>Classificações *</label><div className="cliente-checks">{(['cliente', 'fornecedor', 'transportadora'] as ClassificacaoChave[]).map((key) => <label key={key}><input type="checkbox" checked={form.classificacoes.includes(key)} onChange={() => toggleClass(key)} />{key}</label>)}</div></div><div className="full"><label>Observações internas</label><textarea value={form.observacoes_internas || ''} onChange={(event) => update('observacoes_internas', event.target.value)} /></div></div>}
    {section === 'contatos' && <div><div className="cliente-contact-actions"><Button type="button" size="sm" icon={<Plus size={15} />} onClick={() => update('contatos', [...form.contatos, emptyContact()])}>Adicionar contato</Button></div>{form.contatos.map((contact, index) => <div className="cliente-contact" key={contact.id || index}><div className="cliente-form-grid"><div><label>Nome *</label><Input value={contact.nome} onChange={(event) => updateContact(index, 'nome', event.target.value)} /></div><div><label>Cargo</label><Input value={contact.cargo || ''} onChange={(event) => updateContact(index, 'cargo', event.target.value)} /></div><div><label>Departamento</label><Input value={contact.departamento || ''} onChange={(event) => updateContact(index, 'departamento', event.target.value)} /></div><div><label>Telefone</label><Input value={phoneMask(contact.telefone || '')} onChange={(event) => updateContact(index, 'telefone', phoneMask(event.target.value))} /></div><div><label>WhatsApp</label><Input value={phoneMask(contact.whatsapp || '')} onChange={(event) => updateContact(index, 'whatsapp', phoneMask(event.target.value))} /></div><div><label>E-mail</label><Input type="email" value={contact.email || ''} onChange={(event) => updateContact(index, 'email', event.target.value)} /></div><div className="cliente-checks"><label><input type="checkbox" checked={contact.aprova_orcamentos} onChange={(event) => updateContact(index, 'aprova_orcamentos', event.target.checked)} />Aprova orçamentos</label><label><input type="checkbox" checked={contact.is_principal} onChange={(event) => updateContact(index, 'is_principal', event.target.checked)} />Contato principal</label></div>{form.contatos.length > 1 && <div className="cliente-contact-actions"><Button type="button" size="sm" variant="danger" icon={<Trash2 size={14} />} onClick={() => update('contatos', form.contatos.filter((_, position) => position !== index))}>Remover</Button></div>}</div></div>)}</div>}
    {section === 'cobranca' && <div className="cliente-form-grid"><div><label>CEP *</label><Input value={cepMask(form.endereco_cobranca.cep)} onChange={(event) => update('endereco_cobranca', { ...form.endereco_cobranca, cep: digits(event.target.value) })} />{cepLoading && <small>Consultando CEP…</small>}{cepError && <small className="cliente-field-error">{cepError} <button type="button" onClick={() => void lookupCep(true)}>Tentar novamente</button></small>}</div><div className="wide"><label>Logradouro *</label><Input value={form.endereco_cobranca.logradouro} onChange={(event) => update('endereco_cobranca', { ...form.endereco_cobranca, logradouro: event.target.value })} /></div><div><label>Número</label><Input value={form.endereco_cobranca.numero || ''} onChange={(event) => update('endereco_cobranca', { ...form.endereco_cobranca, numero: event.target.value })} /></div><div><label>Complemento</label><Input value={form.endereco_cobranca.complemento || ''} onChange={(event) => update('endereco_cobranca', { ...form.endereco_cobranca, complemento: event.target.value })} /></div><div><label>Bairro</label><Input value={form.endereco_cobranca.bairro || ''} onChange={(event) => update('endereco_cobranca', { ...form.endereco_cobranca, bairro: event.target.value })} /></div><div><label>Cidade *</label><Input value={form.endereco_cobranca.cidade} onChange={(event) => update('endereco_cobranca', { ...form.endereco_cobranca, cidade: event.target.value })} /></div><div><label>UF *</label><Select value={form.endereco_cobranca.estado} onChange={(event) => update('endereco_cobranca', { ...form.endereco_cobranca, estado: event.target.value })} options={states.map((item) => ({ value: item, label: item }))} /></div></div>}
    {section === 'comercial' && <div className="cliente-form-grid"><div className="full"><label>Condição de pagamento padrão</label><Input value={form.condicao_pagamento_padrao || ''} placeholder="Ex.: 30/60 dias, entrada + saldo ou conforme contrato" onChange={(event) => update('condicao_pagamento_padrao', event.target.value)} /></div><div><label>Limite de faturamento (R$)</label><Input type="number" min="0" step="0.01" disabled={form.sem_limite_faturamento} value={form.limite_faturamento ?? ''} onChange={(event) => update('limite_faturamento', event.target.value === '' ? null : Number(event.target.value))} /></div><div className="cliente-checks"><label><input type="checkbox" checked={Boolean(form.sem_limite_faturamento)} onChange={(event) => update('sem_limite_faturamento', event.target.checked)} />Sem limite de faturamento</label></div><div className="full"><label>Responsável interno</label><Input list="responsaveis-opcoes" placeholder="Pesquise pelo nome ou deixe em branco" value={users.find((user) => user.id === form.responsavel_id)?.name || ''} onChange={(event) => { const selected = users.find((user) => user.name === event.target.value); update('responsavel_id', selected?.id || null); }} /><datalist id="responsaveis-opcoes">{users.map((user) => <option value={user.name} key={user.id} />)}</datalist></div></div>}
    {['documentos', 'filiais', 'obras', 'timeline'].includes(section) && <div className="cliente-empty-inline">Esta seção será preenchida pelos dados reais quando o respectivo endpoint estiver disponível.</div>}<div className="form-actions"><Button type="button" variant="secondary" onClick={() => navigate('/comercial/clientes')}>Cancelar</Button><Button type="submit" loading={saving} disabled={saving}>{editing ? 'Salvar' : 'Cadastrar cliente'}</Button></div></section></form></div>;
}
