import { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { Button, Card, CardBody, CardHeader, CardTitle, Input, Select } from '../../components/ui';
import { useApi } from '../../hooks/useApi';
import * as clienteService from '../../services/comercial/cliente';
import * as orcamentoService from '../../services/comercial/orcamento';
import '../../styles/comercial.css';

export default function OrcamentoForm() {
  const navigate = useNavigate(); const buscarClientes = useCallback(() => clienteService.listarClientes({ limit: 100, status: 'ativo' }), []); const { data, loading, refetch } = useApi(buscarClientes);
  const [clienteId, setClienteId] = useState(''); const [descricao, setDescricao] = useState(''); const [quantidade, setQuantidade] = useState('1'); const [valor, setValor] = useState(''); const [validade, setValidade] = useState(''); const [salvando, setSalvando] = useState(false); const [erro, setErro] = useState('');
  useEffect(() => { refetch(); }, [refetch]);
  const opcoes = (data?.data ?? []).map((cliente) => ({ value: String(cliente.id), label: cliente.documento ? `${cliente.nome} (${cliente.documento})` : cliente.nome }));
  const total = useMemo(() => Number(quantidade || 0) * Number(valor || 0), [quantidade, valor]);
  const salvar = async (event: React.FormEvent) => { event.preventDefault(); setErro(''); if (!clienteId || !descricao || total <= 0) { setErro('Selecione o cliente, informe o item e um valor válido.'); return; } try { setSalvando(true); await orcamentoService.criarOrcamentoDireto({ cliente_id: Number(clienteId), validade_ate: validade || undefined, itens: [{ descricao, quantidade: Number(quantidade), unidade: 'un', valor_unitario: Number(valor) }] }); navigate('/comercial/orcamentos'); } catch (error) { setErro(error instanceof Error ? error.message : 'Não foi possível criar o orçamento.'); } finally { setSalvando(false); } };
  return <div className="comercial-container"><div className="comercial-header"><Button variant="ghost" icon={<ArrowLeft size={20} />} onClick={() => navigate('/comercial/orcamentos')}>Voltar</Button></div><Card><CardHeader><CardTitle>Novo Orçamento</CardTitle></CardHeader><CardBody><form onSubmit={salvar} className="form-grid"><div className="form-group form-group-full"><label>Cliente</label><Select value={clienteId} onChange={(event) => setClienteId(event.target.value)} options={opcoes} placeholder={loading ? 'Carregando clientes...' : 'Selecione o cliente'} disabled={loading} /></div><div className="form-group form-group-full"><label>Item / escopo</label><Input value={descricao} onChange={(event) => setDescricao(event.target.value)} placeholder="Ex.: Estrutura metálica para cobertura" /></div><div className="form-group"><label>Quantidade</label><Input type="number" min="0.01" step="0.01" value={quantidade} onChange={(event) => setQuantidade(event.target.value)} /></div><div className="form-group"><label>Valor unitário</label><Input type="number" min="0.01" step="0.01" value={valor} onChange={(event) => setValor(event.target.value)} placeholder="0,00" /></div><div className="form-group"><label>Validade</label><Input type="date" value={validade} onChange={(event) => setValidade(event.target.value)} /></div><div className="form-group"><label>Total estimado</label><Input readOnly value={new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(total)} /></div>{erro && <div className="error-message form-group-full">{erro}</div>}<div className="form-actions"><Button type="button" variant="secondary" onClick={() => navigate('/comercial/orcamentos')}>Cancelar</Button><Button type="submit" loading={salvando}>Criar orçamento</Button></div></form></CardBody></Card></div>;
}
