import type { ChartPoint } from '../types';

interface MetricChartProps { title: string; subtitle: string; value: string; points: ChartPoint[]; variant: 'bar' | 'line'; indicators: Array<{ label: string; value: string }>; }

export function MetricChart({ title, subtitle, value, points, variant, indicators }: MetricChartProps) {
  if (points.length === 0) return <section className="cockpit-panel cockpit-chart"><div className="cockpit-panel-heading"><div><p className="cockpit-overline">Indicador</p><h2>{title}</h2><p className="cockpit-panel-subtitle">{subtitle}</p></div></div><div className="cockpit-empty-state">Ainda não há dados para este período.</div></section>;
  const maxValue = Math.max(...points.map((point) => point.value));
  const coordinates = points.map((point, index) => `${(index / Math.max(points.length - 1, 1)) * 100},${90 - (point.value / Math.max(maxValue, 1)) * 72}`).join(' ');

  return <section className={`cockpit-panel cockpit-chart cockpit-chart-${variant}`}><div className="cockpit-panel-heading"><div><p className="cockpit-overline">Indicador semanal</p><h2>{title}</h2><p className="cockpit-panel-subtitle">{subtitle}</p></div><strong className="cockpit-chart-value">{value}</strong></div><div className="cockpit-chart-indicators">{indicators.map((indicator) => <div key={indicator.label}><span>{indicator.label}</span><strong>{indicator.value}</strong></div>)}</div>{variant === 'bar' ? <div className="cockpit-bar-chart" aria-label={`${title}: ${value}`}>{points.map((point) => <div className="cockpit-bar-column" key={point.label}><div className="cockpit-bar-track"><span style={{ height: `${Math.max((point.value / Math.max(maxValue, 1)) * 100, 8)}%` }} /></div><small>{point.label}</small></div>)}</div> : <div className="cockpit-line-chart" aria-label={`${title}: ${value}`}><svg viewBox="0 0 100 100" role="img" aria-label={title} preserveAspectRatio="none"><defs><linearGradient id="revenue-area" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#34d399" stopOpacity=".34" /><stop offset="100%" stopColor="#34d399" stopOpacity="0" /></linearGradient></defs><path className="cockpit-chart-grid" d="M0 18H100M0 54H100M0 90H100" /><polygon points={`0,90 ${coordinates} 100,90`} fill="url(#revenue-area)" /><polyline points={coordinates} className="cockpit-line-path" /></svg><div className="cockpit-line-labels">{points.map((point) => <small key={point.label}>{point.label}</small>)}</div></div>}</section>;
}
